# [Minetest](http://www.minetest.net/) (server) is a near-infinite-world block
# sandbox game and a game engine, inspired by InfiniMiner, Minecraft, and the
# like.

---
version: "2.1"
services:
  minetest:
    image: ghcr.io/linuxserver/minetest
    container_name: minetest
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
      # Optionally specify any [CLI variables](https://wiki.minetest.net/Command_line) you want to launch the app with
      - CLI_ARGS=--gameid devtest # optional
    volumes:
      # Where minetest stores config files and maps etc.
      - ${BASEDIR:-/volume1/docker}/minetest/config/.minetest:/config/.minetest
    ports:
      # Port Minetest listens on (UDP).
      - 30000:30000/udp
    restart: unless-stopped
