# [MySQL Workbench](https://www.mysql.com/products/workbench/) is a unified
# visual tool for database architects, developers, and DBAs. MySQL Workbench
# provides data modeling, SQL development, and comprehensive administration
# tools for server configuration, user administration, backup, and much more.

---
version: "2.1"
services:
  mysql-workbench:
    image: ghcr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    cap_add:
      - IPC_LOCK
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Users home directory in the container, stores program settings.
      - ${BASEDIR:-/volume1/docker}/mysql-workbench/config:/config
    ports:
      # Mysql Workbench desktop gui.
      - 3000:3000
      # Mysql Workbench desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
