# [VLC Media Player](https://www.videolan.org/vlc/) is a free and open source
# cross-platform multimedia player and framework that delivers dependable
# performance across multiple devices.

---
services:
  vlc:
    image: lscr.io/linuxserver/vlc:latest
    container_name: vlc
    environment:
      # Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
      - PUID=${PUID:-1000}
      # Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
      - PGID=${PGID:-1000}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Etc/UTC}
      # Specify one or multiple VLC CLI flags, this string will be passed to the application in full. [OPTIONAL]
      - VLC_CLI=--no-qt-minimal-view
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/srv/lsio}/vlc/config:/config
    ports:
      # VLC Media Player desktop gui HTTP must be proxied.
      - 3000:3000
      # VLC Media Player desktop gui HTTPS.
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped