# [Changedetection.io](https://github.com/dgtlmoon/changedetection.io) provides
# free, open-source web page monitoring, notification and change detection.

---
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL= #optional
      - PLAYWRIGHT_DRIVER_URL= #optional
    volumes:
      - /path/to/changedetection/config:/config
    ports:
      - 5000:5000
    restart: unless-stopped

