# [Signal](https://signal.org/) is a messaging app with privacy at its core. It
# is free and easy to use, with strong end-to-end encryption that keeps your
# communication completely private.

---
services:
  signal:
    image: lscr.io/linuxserver/signal:latest
    container_name: signal
    environment:
      # Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
      - PUID=${PUID:-1000}
      # Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
      - PGID=${PGID:-1000}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Etc/UTC}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/srv/lsio}/signal/config:/config
    ports:
      # Signal desktop gui HTTP must be proxied.
      - 3000:3000
      # Signal desktop gui HTTPS.
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped