# [Azahar](https://azahar-emu.org/) is an open-source 3DS emulator based on
# Citra.

---
services:
  azahar:
    image: lscr.io/linuxserver/azahar:latest
    container_name: azahar
    environment:
      # Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
      - PUID=${PUID:-1000}
      # Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
      - PGID=${PGID:-1000}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Etc/UTC}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/srv/lsio}/azahar/config:/config
    ports:
      # Azahar desktop gui HTTP must be proxied.
      - 3000:3000
      # Azahar desktop gui HTTPS.
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped