# [HandBrake](https://handbrake.fr/) is an open-source tool, built by
# volunteers, for converting video from nearly any format to a selection of
# modern, widely supported codecs.

---
services:
  handbrake:
    image: lscr.io/linuxserver/handbrake:latest
    container_name: handbrake
    environment:
      # Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
      - PUID=${PUID:-1000}
      # Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
      - PGID=${PGID:-1000}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Etc/UTC}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/srv/lsio}/handbrake/config:/config
    ports:
      # HandBrake desktop gui HTTP must be proxied.
      - 3000:3000
      # HandBrake desktop gui HTTPS.
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped