# [melonDS](https://melonds.kuribo64.net/) aims at providing fast and accurate
# Nintendo DS emulation.

---
services:
  melonds:
    image: lscr.io/linuxserver/melonds:latest
    container_name: melonds
    environment:
      # Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
      - PUID=${PUID:-1000}
      # Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
      - PGID=${PGID:-1000}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Etc/UTC}
    volumes:
      # Users home directory in the container, stores program settings and files.
      - ${BASEDIR:-/srv/lsio}/melonds/config:/config
    ports:
      # melonDS desktop gui HTTP, must be proxied.
      - 3000:3000
      # melonDS desktop gui HTTPS.
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped