# [Nntp2nntp](https://github.com/linuxserver/nntp2nntp) proxy allow you to use
# your NNTP Account from multiple systems, each with own user name and password.
# It fully supports SSL and you can also limit the access to proxy with SSL
# certificates. nntp2nntp proxy is very simple and pretty fast. ## Warning
# Whilst we know of no nntp2nntp security issues the [upstream
# code](https://github.com/linuxserver/nntp2nntp) for this project has received
# no changes since 06.08.15 and is likely abandoned permanently. For this reason
# we strongly recommend you do not make this application public facing and if
# you must do so other layers of security and SSL should be considered an
# absolute bare minimum requirement. We see this proxy being used primarily on a
# LAN so that all the users NNTP applications can share a common set of internal
# credentials allowing for central managment of the upstream account e.g change
# provider, server, thread limits for all applications with one global config
# change.

---
version: "2.1"
services:
  nntp2nntp:
    image: ghcr.io/linuxserver/nntp2nntp
    container_name: nntp2nntp
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # specify your UID
      - PUID=<yourUID>
      # specify your GID
      - PGID=<yourGID>
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # this will store config on the docker host
      - ${BASEDIR:-/volume1/docker}/nntp2nntp/config:/config
    ports:
      # will map the container's port 1563 to port 1563 on the host
      - 1563:1563
    restart: unless-stopped
